"""
Voltage-dependent STDP / Fig. 2b sanity-check code.

Purpose
-------
This script is a cleaned-up Brian2 version of the voltage_STDP code used to
understand Fig. 2b. It is not a full paper reproduction; it is a compact
mechanism check showing how postsynaptic depolarization changes NMDA-driven
E_trace and therefore excitatory weight change.

Main equations implemented
--------------------------
    tau_m du/dt = -(u-u_rest) - g_AMPA u - g_NMDA H_NMDA(u) u
                  - g_bAP (u-E_bAP) + I_clamp

    dE/dt = (-E + max(-g_NMDA H_NMDA(u) u, 0)) / tau_E

    pre event:
        g_AMPA += wE
        g_NMDA += wE
        wE *= (1 - A_LTD y_post_LTD)
        x_pre += 1

    post/bAP event:
        g_bAP += ca_amp
        wE += A_LTP x_pre E - A_het y_post_het E^2
        y_post_LTD += 1
        y_post_het += 1

Notes
-----
- post events are prescribed by a SpikeGeneratorGroup. They are interpreted as
  experimentally imposed postsynaptic spike/bAP events, not as threshold events
  generated by this one-compartment model.
- Brian2 is required only for simulation. Plot-only mode works without Brian2.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    from brian2 import (  # type: ignore
        SpikeGeneratorGroup,
        Synapses,
        NeuronGroup,
        StateMonitor,
        Network,
        ms,
        second,
        defaultclock,
        prefs,
        start_scope,
    )
    BRIAN2_AVAILABLE = True
except Exception:  # pragma: no cover - used on systems without Brian2
    BRIAN2_AVAILABLE = False


@dataclass(frozen=True)
class Protocol:
    pre_times_ms: np.ndarray
    post_times_ms: np.ndarray
    duration_ms: float
    quiet_1_ms: float
    burst_duration_ms: float
    rep_duration_ms: float


def require_brian2() -> None:
    if not BRIAN2_AVAILABLE:
        raise RuntimeError(
            "Brian2 is not installed. Install it with `pip install brian2`, "
            "or use --plot-only with an existing CSV."
        )


def set_brian_target(target: str) -> None:
    require_brian2()
    prefs.codegen.target = target
    defaultclock.dt = 0.1 * ms


def make_protocol(
    n_reps: int = 15,
    n_pairs_per_burst: int = 5,
    quiet_1_ms: float = 5000.0,
    burst_duration_ms: float = 100.0,
    quiet_2_ms: float = 5000.0,
    pre_offset_ms: float = 10.0,
    post_offset_ms: float = 20.0,
    pair_interval_ms: float = 20.0,
) -> Protocol:
    """Return repeated pre/post pairing times.

    Default protocol gives pre-before-post with Delta t = +10 ms:
        pre  = base + 10 + 20*n ms
        post = base + 20 + 20*n ms
    """
    pre_times: List[float] = []
    post_times: List[float] = []
    rep_duration_ms = quiet_1_ms + burst_duration_ms + quiet_2_ms

    for k in range(n_reps):
        base = k * rep_duration_ms + quiet_1_ms
        for n in range(n_pairs_per_burst):
            pre_times.append(base + pre_offset_ms + pair_interval_ms * n)
            post_times.append(base + post_offset_ms + pair_interval_ms * n)

    duration_ms = n_reps * rep_duration_ms
    return Protocol(
        pre_times_ms=np.asarray(pre_times, dtype=float),
        post_times_ms=np.asarray(post_times, dtype=float),
        duration_ms=float(duration_ms),
        quiet_1_ms=float(quiet_1_ms),
        burst_duration_ms=float(burst_duration_ms),
        rep_duration_ms=float(rep_duration_ms),
    )


def default_params(inp_clamp: float, ca_amp: float) -> Dict[str, object]:
    require_brian2()
    return {
        # neuron
        "tau_m": 30.0 * ms,
        "u_rest": -65.0,
        "E_bap": 50.0,
        # synaptic currents
        "tau_ampa": 5.0 * ms,
        "tau_nmda": 150.0 * ms,
        "tau_bap": 1.0 * ms,
        "tau_E": 50.0 * ms,
        "a_nmda": 0.15,
        "b_nmda": -0.08,
        # traces
        "tau_pre": 16.8 * ms,
        "tau_post_ltd": 33.7 * ms,
        "tau_post_het": 100.0 * ms,
        # plasticity. These are deliberately compact/sanity-check values.
        "A_ltp": 0.00025,
        "A_ltd": 0.000398,
        "A_het": 1e-9,
        "wmin": 1e-5,
        "wmax": 1.0,
        # manipulation variables
        "inp_clamp": float(inp_clamp),
        "ca_amp": float(ca_amp),
    }


def event_window_mask(t_ms: np.ndarray, event_times_ms: np.ndarray, pre_ms: float = 0.0, post_ms: float = 5.0) -> np.ndarray:
    mask = np.zeros_like(t_ms, dtype=bool)
    for ev in event_times_ms:
        mask |= (t_ms >= ev - pre_ms) & (t_ms <= ev + post_ms)
    return mask


def compute_depolarization_metrics(t_ms: np.ndarray, u: np.ndarray, protocol: Protocol, u_rest: float) -> Dict[str, float]:
    burst_mask = np.zeros_like(t_ms, dtype=bool)
    for k in range(int(np.ceil(protocol.duration_ms / protocol.rep_duration_ms))):
        start = k * protocol.rep_duration_ms + protocol.quiet_1_ms
        stop = start + protocol.burst_duration_ms
        burst_mask |= (t_ms >= start) & (t_ms < stop)

    event_mask = event_window_mask(t_ms, protocol.post_times_ms, pre_ms=0.0, post_ms=5.0)

    if np.any(burst_mask):
        mean_burst_u = float(np.mean(u[burst_mask]))
        peak_burst_u = float(np.max(u[burst_mask]))
    else:
        mean_burst_u = float(np.mean(u))
        peak_burst_u = float(np.max(u))

    if np.any(event_mask):
        mean_event_u = float(np.mean(u[event_mask]))
        peak_event_u = float(np.max(u[event_mask]))
    else:
        mean_event_u = mean_burst_u
        peak_event_u = peak_burst_u

    return {
        "avg_u_burst": mean_burst_u,
        "peak_u_burst": peak_burst_u,
        "avg_u_event": mean_event_u,
        "peak_u_event": peak_event_u,
        "depol_burst_mean": mean_burst_u - u_rest,
        "depol_burst_peak": peak_burst_u - u_rest,
        "depol_event_mean": mean_event_u - u_rest,
        "depol_event_peak": peak_event_u - u_rest,
    }


def run_one_condition(
    w0: float = 0.005,
    inp_clamp: float = 0.0,
    ca_amp: float = 0.0,
    target: str = "numpy",
    record_dt_ms: float = 1.0,
    make_plots: bool = True,
    outdir: str | Path = "results_voltage_single_final",
) -> Dict[str, float]:
    """Run one voltage-dependent STDP condition."""
    set_brian_target(target)
    start_scope()
    defaultclock.dt = 0.1 * ms

    ns = default_params(inp_clamp=inp_clamp, ca_amp=ca_amp)
    protocol = make_protocol()

    pre_group = SpikeGeneratorGroup(
        1,
        indices=np.zeros(len(protocol.pre_times_ms), dtype=int),
        times=protocol.pre_times_ms * ms,
    )

    post_group = SpikeGeneratorGroup(
        1,
        indices=np.zeros(len(protocol.post_times_ms), dtype=int),
        times=protocol.post_times_ms * ms,
    )

    eqs = """
    du/dt = (-(u - u_rest)
             - g_ampa * u
             - g_nmda * H_nmda * u
             - g_bap * (u - E_bap)
             + inp_clamp) / tau_m : 1

    dg_ampa/dt = -g_ampa / tau_ampa : 1
    dg_nmda/dt = -g_nmda / tau_nmda : 1
    dg_bap/dt = -g_bap / tau_bap : 1

    dE_trace/dt = (-E_trace + I_nmda_src) / tau_E : 1

    dxpre/dt = -xpre / tau_pre : 1
    dypost_ltd/dt = -ypost_ltd / tau_post_ltd : 1
    dypost_het/dt = -ypost_het / tau_post_het : 1

    H_nmda = 1.0 / (1.0 + a_nmda * exp(b_nmda * u)) : 1
    I_nmda_src = clip(-g_nmda * H_nmda * u, 0.0, 1e6) : 1
    E_for_plasticity = clip(E_trace, 0.0, 1e6) : 1

    wE : 1
    """

    G = NeuronGroup(1, eqs, method="euler", namespace=ns)
    G.u = ns["u_rest"]
    G.g_ampa = 0.0
    G.g_nmda = 0.0
    G.g_bap = 0.0
    G.E_trace = 0.0
    G.xpre = 0.0
    G.ypost_ltd = 0.0
    G.ypost_het = 0.0
    G.wE = w0

    Spre = Synapses(
        pre_group,
        G,
        on_pre="""
        g_ampa_post += wE_post
        g_nmda_post += wE_post
        wE_post = clip(wE_post * (1.0 - A_ltd * ypost_ltd_post), wmin, wmax)
        xpre_post += 1.0
        """,
        namespace=ns,
    )
    Spre.connect()

    Spost = Synapses(
        post_group,
        G,
        on_pre="""
        g_bap_post += ca_amp
        wE_post = clip(wE_post + A_ltp * xpre_post * E_for_plasticity_post - A_het * ypost_het_post * (E_for_plasticity_post ** 2), wmin, wmax)
        ypost_ltd_post += 1.0
        ypost_het_post += 1.0
        """,
        namespace=ns,
    )
    Spost.connect()

    M = StateMonitor(
        G,
        ["u", "g_ampa", "g_nmda", "g_bap", "H_nmda", "E_trace", "I_nmda_src", "wE"],
        record=True,
        dt=record_dt_ms * ms,
    )

    net = Network(G, pre_group, post_group, Spre, Spost, M)
    net.run(protocol.duration_ms * ms)

    t_ms = np.asarray(M.t / ms)
    u = np.asarray(M.u[0])
    depol_metrics = compute_depolarization_metrics(t_ms, u, protocol, float(ns["u_rest"]))

    final_w = float(G.wE[0])
    final_percent = 100.0 * final_w / float(w0)

    result: Dict[str, float] = {
        "w0": float(w0),
        "inp_clamp": float(inp_clamp),
        "ca_amp": float(ca_amp),
        "final_w": final_w,
        "final_percent": final_percent,
        "delta_percent": final_percent - 100.0,
        "peak_E_trace": float(np.max(M.E_trace[0])),
        "mean_E_trace": float(np.mean(M.E_trace[0])),
        "peak_g_nmda": float(np.max(M.g_nmda[0])),
        "peak_g_ampa": float(np.max(M.g_ampa[0])),
        **depol_metrics,
    }
    # Keep the old key for compatibility with earlier sweep scripts.
    result["depol"] = result["depol_event_mean"]

    if make_plots:
        outdir = Path(outdir)
        outdir.mkdir(parents=True, exist_ok=True)
        plot_single_traces(M, outdir)
        pd.DataFrame([result]).to_csv(outdir / "single_condition_summary.csv", index=False)

    return result


def plot_single_traces(M, outdir: Path) -> None:
    t_s = np.asarray(M.t / second)

    fig, axes = plt.subplots(4, 1, figsize=(9, 9), sharex=True)
    axes[0].plot(t_s, M.u[0])
    axes[0].set_ylabel("u")
    axes[0].set_title("Voltage-dependent STDP example")

    axes[1].plot(t_s, M.g_nmda[0], label="g_NMDA")
    axes[1].plot(t_s, M.g_ampa[0], label="g_AMPA")
    axes[1].set_ylabel("conductance")
    axes[1].legend(fontsize=8)

    axes[2].plot(t_s, M.E_trace[0], label="E trace")
    axes[2].plot(t_s, M.I_nmda_src[0], alpha=0.6, label="NMDA source")
    axes[2].set_ylabel("E")
    axes[2].legend(fontsize=8)

    axes[3].plot(t_s, M.wE[0])
    axes[3].set_ylabel("wE")
    axes[3].set_xlabel("time (s)")

    fig.tight_layout()
    fig.savefig(outdir / "voltage_single_diagnostics.png", dpi=200)
    plt.close(fig)

    # Individual plots for slide insertion.
    for name, y, ylabel in [
        ("u_trace", M.u[0], "membrane potential u"),
        ("E_trace", M.E_trace[0], "E trace"),
        ("wE_trace", M.wE[0], "wE"),
    ]:
        plt.figure(figsize=(8, 4))
        plt.plot(t_s, y)
        plt.xlabel("time (s)")
        plt.ylabel(ylabel)
        plt.tight_layout()
        plt.savefig(outdir / f"{name}.png", dpi=200)
        plt.close()

    plt.figure(figsize=(8, 4))
    plt.plot(t_s, M.g_nmda[0], label="g_NMDA")
    plt.plot(t_s, M.g_ampa[0], label="g_AMPA")
    plt.xlabel("time (s)")
    plt.ylabel("conductance")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outdir / "conductances.png", dpi=200)
    plt.close()


def sweep_grid(mode: str) -> Tuple[int, int, int]:
    if mode == "quick":
        return 3, 8, 12
    if mode == "medium":
        return 5, 15, 18
    if mode == "full":
        return 5, 25, 999
    raise ValueError("mode must be quick, medium, or full")


def run_sweep(mode: str, target: str, outdir: str | Path) -> pd.DataFrame:
    """Run a compact version of the voltage sweep used for Fig. 2b."""
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    n_weight, n_clamp, max_ca_steps = sweep_grid(mode)
    p_sim_3 = 0.04
    p_sim_4 = 0.005 - p_sim_3

    rows: List[Dict[str, float]] = []
    for k0 in range(1, n_weight + 1):
        w0 = p_sim_4 + p_sim_3 * k0
        inp_clamp = 0.0

        for k1 in range(1, n_clamp + 1):
            if k1 == 1:
                inp_clamp = 0.0
            else:
                inp_clamp += 10.0 ** (0.12 * float(k1 - 2) - 2.0)

            for k in range(1, max_ca_steps + 1):
                v_inf = 10.0 ** (0.04 * float(k - 1) - 1.0)
                ca_amp = v_inf / (50.0 - (-65.0) - v_inf)
                ca_amp = ca_amp / (50.0 * 0.05)
                if k == 1:
                    ca_amp = 0.0

                print(
                    "running:",
                    "k0", k0,
                    "k1", k1,
                    "k", k,
                    "w0", w0,
                    "inp_clamp", inp_clamp,
                    "ca_amp", ca_amp,
                )

                result = run_one_condition(
                    w0=w0,
                    inp_clamp=inp_clamp,
                    ca_amp=ca_amp,
                    target=target,
                    record_dt_ms=1.0,
                    make_plots=False,
                )
                result["k0"] = float(k0)
                result["k1"] = float(k1)
                result["k_ca"] = float(k)
                rows.append(result)

                pd.DataFrame(rows).to_csv(outdir / f"voltage_stdp_sweep_{mode}_raw.csv", index=False)

                # Full mode follows the old stop rule. Quick/medium use max_ca_steps.
                if mode == "full" and result["depol_event_mean"] > 7.0:
                    break

    df = pd.DataFrame(rows)
    df.to_csv(outdir / f"voltage_stdp_sweep_{mode}_raw.csv", index=False)
    plot_sweep(df, outdir, mode)
    return df


def plot_sweep(df: pd.DataFrame, outdir: str | Path, mode: str) -> None:
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    # Main plot: mean depolarization around post/bAP events.
    plt.figure(figsize=(6, 4))
    plt.scatter(df["depol_event_mean"], df["final_percent"], s=12, alpha=0.75)
    plt.axhline(100.0, linewidth=1.0)
    plt.xlabel("mean depolarization near post events")
    plt.ylabel("final weight / initial weight (%)")
    plt.title(f"Voltage-dependent STDP sweep ({mode})")
    plt.tight_layout()
    plt.savefig(outdir / f"fig2b_voltage_scatter_{mode}_final.png", dpi=200)
    plt.close()

    # Alternative plot: peak depolarization, useful when bAP is brief.
    plt.figure(figsize=(6, 4))
    plt.scatter(df["depol_event_peak"], df["final_percent"], s=12, alpha=0.75)
    plt.axhline(100.0, linewidth=1.0)
    plt.xlabel("peak depolarization near post events")
    plt.ylabel("final weight / initial weight (%)")
    plt.title(f"Voltage dependence, peak metric ({mode})")
    plt.tight_layout()
    plt.savefig(outdir / f"fig2b_voltage_peak_scatter_{mode}_final.png", dpi=200)
    plt.close()

    # Diagnostic plot: E_trace increases with depolarization.
    plt.figure(figsize=(6, 4))
    plt.scatter(df["depol_event_mean"], df["peak_E_trace"], s=12, alpha=0.75)
    plt.xlabel("mean depolarization near post events")
    plt.ylabel("peak E trace")
    plt.title(f"Depolarization increases NMDA-driven E ({mode})")
    plt.tight_layout()
    plt.savefig(outdir / f"voltage_Etrace_scatter_{mode}_final.png", dpi=200)
    plt.close()


def plot_only(csv_path: str | Path, mode: str, outdir: str | Path) -> None:
    df = pd.read_csv(csv_path)
    # Compatibility with older CSVs.
    if "depol_event_mean" not in df.columns and "depol" in df.columns:
        df["depol_event_mean"] = df["depol"]
    if "depol_event_peak" not in df.columns:
        df["depol_event_peak"] = df["depol_event_mean"]
    if "peak_E_trace" not in df.columns:
        df["peak_E_trace"] = np.nan
    plot_sweep(df, Path(outdir), mode)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["single", "quick", "medium", "full"], default="single")
    parser.add_argument("--target", choices=["numpy", "cython"], default="numpy")
    parser.add_argument("--outdir", default=None)
    parser.add_argument("--plot-only", action="store_true")
    parser.add_argument("--csv", default=None, help="Existing sweep CSV for --plot-only.")
    parser.add_argument("--w0", type=float, default=0.005)
    parser.add_argument("--inp-clamp", type=float, default=0.0)
    parser.add_argument("--ca-amp", type=float, default=0.05)
    parser.add_argument("--record-dt-ms", type=float, default=1.0)
    args = parser.parse_args()

    outdir = Path(args.outdir) if args.outdir else Path(f"results_voltage_stdp_final_{args.mode}")

    if args.plot_only:
        if args.csv is None:
            raise ValueError("--plot-only requires --csv")
        plot_only(args.csv, mode=args.mode, outdir=outdir)
        print("saved:", outdir.resolve())
        return

    if args.mode == "single":
        result = run_one_condition(
            w0=args.w0,
            inp_clamp=args.inp_clamp,
            ca_amp=args.ca_amp,
            target=args.target,
            record_dt_ms=args.record_dt_ms,
            make_plots=True,
            outdir=outdir,
        )
        print(pd.Series(result))
    else:
        run_sweep(mode=args.mode, target=args.target, outdir=outdir)

    print("saved:", outdir.resolve())


if __name__ == "__main__":
    main()
